services:
  postgres:
    image: postgres:16
    container_name: library_postgres
    restart: always
    environment:
      POSTGRES_USER: libraryuser
      POSTGRES_PASSWORD: librarypass
      POSTGRES_DB: librarydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U libraryuser -d librarydb"]
      interval: 5s
      timeout: 5s
      retries: 10

  library_api:
    build: .
    container_name: library_api
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_USER: libraryuser
      POSTGRES_PASSWORD: librarypass
      POSTGRES_DB: librarydb
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      DATABASE_URL: "postgresql://libraryuser:librarypass@postgres:5432/librarydb"
    ports:
      - "8000:8000"

volumes:
  postgres_data:

